- tests/test_rest_api.py
- tests/test_utils.py
Small improvements in test coverage - tests for readiness and liveness REST API end points.
> Liveness and readiness checks

- src/rest_api.py
- src/utils.py
- tests/test_rest_api.py
Minor change from `_` to `-` :)
> Change dictionary keys to reflect keys from scanner

- src/rest_api.py
- /report endpoint now accepts both repo url and sha as parameters.
> Update /report endpoint

- src/rest_api.py
- Invoke scan for input commit hash if no report is available.
- Don't send report for (n-1)th commit if no report for nth commit is available.
> Change behavior of register endpoint

- Dockerfile.rhel
- Makefile
- cico_setup.sh
Depends on https://github.com/openshiftio/openshiftio-cico-jobs/pull/632 to be merged first.
> Move to RHEL

- src/rest_api.py
- Make sure that the scan is invoked irrespective of results are available or not.
> Update register endpoint to trigger scan

- cico_setup.sh
- runtests.sh
- The current version of virtual env is 16.0.0 and it's failing the builds.
> Downgrade a version of virtual env

- check-bashscripts.sh
- runtests.sh
https://github.com/openshiftio/openshift.io/issues/3751
> Script to check bash script

- README.md
> Updated README.md: info about scripts to detect dead code and common issues

- src/utils.py
Reverts fabric8-analytics/fabric8-gemini-server#87
> Revert "Convert the Git SSH URL to HTTPS"

- src/rest_api.py
- Delete all the edges from graph if user unsubscribes from security notifications.
> Add functionality to drop user repository on unsubscribing

- src/rest_api.py
- We cannot use json payload and files inside a single request and hence changing this to form data
> Use form data for passing git url

- src/parsers/maven_parser.py
- src/repo_dependency_creator.py
- src/rest_api.py
This commit fixes the following:
- Remove direct dependencies from the list of transitive dependencies.
- Reorder the maven parser keys to get proper version.
> Fix minor issues

- openshift/template.yaml
- src/notification/__init__.py
- src/notification/user_notification.py
Signed-off-by: Geetika Batra <gbatra@redhat.com
> Update notification payload for cve

- src/notification/user_notification.py
fixes: https://github.com/openshiftio/openshift.io/issues/4308
> fix undefined name

- src/rest_api.py
Replace authentication method to use service _account_token
> Use service _account_required wrapper for authentication

- requirements.in
- requirements.txt
Fixes https://github.com/openshiftio/openshift.io/issues/4484.
> Remove unused requirements

- check-docstyle.sh
- cico_run_pydoc.sh
- cico_run_pylint.sh
- detect-common-errors.sh
- detect-dead-code.sh
- generate-doc.sh
- measure-cyclomatic-complexity.sh
- measure-maintainability-index.sh
- run-linter.sh
- runtests.sh
- tools/check_python_version.py
Implements https://github.com/fabric8-analytics/fabric8-gemini-server/issues/182
> Check Python version on CI

- src/rest_api.py
- src/utils.py
Fixes key not found issue while requesting stack report.
Fixes # (issue)
https://jira.coreos.com/browse/APPAI-1025
Please delete options that are not relevant.
> handle key not found error

- requirements.txt
- src/rest_api.py
- src/utils.py
- swagger.yaml
- tests/test_rest_api.py
As the code related to cve_source is not in use anymore, removing it from the repo
Fixes #APPAI-1202
> Removal of cve_sources and code related to it

- Dockerfile
- Dockerfile.rhel
- qa/runtests.sh
- setup.py
- src/utils.py
- tests/requirements.in
- tests/requirements.txt
> fix: Unify python dependency installation and update to vulnerability free versions

- src/rest_api.py
Using Gemini secret to verify internal user and authorize to read full data from tables.
> chore: secret modification.
